treblle:
  url: null
  api_key: "%env(TREBLLE_API_KEY)%"
  project_id: "%env(TREBLLE_PROJECT_ID)%"
  ignored_environments: "%env(TREBLLE_IGNORED_ENV)%"
  masked_fields:
    - password
    - pwd
    - secret
    - password_confirmation
    - cc
    - card_number
    - ccb
    - ssn
    - credit_score
    - api_key
  debug: "%env(TREBLLE_DEBUG_MODE)%"